services:
  # Frontend static site
  - type: static
    name: chatbot-frontend
    env: static
    buildCommand: cd chatbot-frontend && npm install && npm run build
    staticPublishPath: ./chatbot-frontend/build
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production